import { ListOrdered, Play } from 'lucide-react'
import type { StageSchedule } from '../types'

interface Props { stage?: StageSchedule; busy?: boolean; isCurrent?: boolean; onStart?: (matchId: string) => void }
export function StageAgenda({ stage, busy = false, isCurrent = true, onStart }: Props) {
  if (!stage?.total) return null
  const current = stage.queue.find(slot => slot.matchId === stage.currentMatchId)
  const next = stage.queue.find(slot => slot.matchId === stage.nextMatchId)
  return <section aria-label="Agenda del escenario" className="admin-section mb-6">
    <div className="section-heading"><div><p className="eyebrow">Un escenario · una batalla a la vez</p><h2>Orden de salida</h2></div><span className="count-badge" aria-label={`${stage.completed} de ${stage.total} batallas terminadas`}>{stage.completed}/{stage.total}</span></div>
    <div className="grid gap-3 sm:grid-cols-2" aria-live="polite">
      <div className="rounded-2xl border border-fuchsia-200 bg-fuchsia-50/70 p-4"><p className="text-xs font-bold uppercase tracking-wider text-fuchsia-800">{current ? current.status === 'paused' ? 'Ahora · pausada' : 'Ahora · en vivo' : next ? 'Cambio de participantes' : 'Agenda completada'}</p><strong className="mt-2 block break-words text-base">{current ? `${current.contestantA} vs ${current.contestantB}` : next ? 'Preparando el escenario' : 'Todas las batallas terminaron'}</strong><p className="mt-1 text-xs text-secondary">{current ? `Turno ${current.number} · ${current.label}` : next ? 'El reloj comienza al dar inicio, no durante la espera.' : 'Consulta la clasificación final.'}</p></div>
      <div className="rounded-2xl border border-white bg-white/70 p-4"><p className="text-xs font-bold uppercase tracking-wider text-secondary">A continuación{next ? ` · turno ${next.number}` : ''}</p><strong className="mt-2 block break-words text-base">{next ? `${next.contestantA} vs ${next.contestantB}` : 'No hay más turnos pendientes'}</strong><p className="mt-1 text-xs text-secondary">{next?.label ?? 'Fin de la agenda'}</p></div>
    </div>
    {onStart && next && <div className="mt-4 flex flex-col items-start gap-2"><button type="button" className="primary-action" disabled={busy || !isCurrent || Boolean(current) || !next.ready} onClick={() => onStart(next.matchId)}><Play size={17} /> Iniciar siguiente batalla</button><p className="text-xs leading-5 text-secondary">{!isCurrent ? 'Lleva esta convocatoria al escenario para comenzar.' : current ? 'Termina la batalla actual antes de abrir el siguiente turno.' : !next.ready ? 'Falta definir a los participantes de este turno.' : 'Úsalo cuando ambos participantes estén listos. No se salta ningún cruce.'}</p></div>}
    <details className="mt-4"><summary className="flex min-h-11 cursor-pointer items-center gap-2 text-sm font-bold"><ListOrdered size={18} /> Ver agenda completa ({stage.total})</summary><ol className="mt-2 grid max-h-80 gap-2 overflow-y-auto pr-1">{stage.queue.map(slot => <li key={slot.matchId} className={`flex items-start gap-3 rounded-xl border p-3 text-sm ${slot.matchId === current?.matchId ? 'border-fuchsia-300 bg-fuchsia-50' : 'border-slate-200/70 bg-white/40'}`}><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-white font-bold tabular-nums">{slot.number}</span><div className="min-w-0 flex-1"><strong className="block break-words">{slot.contestantA} vs {slot.contestantB}</strong><small className="text-secondary">{slot.label}</small></div><span className="shrink-0 text-xs text-secondary">{slot.status === 'finished' ? 'Terminada' : slot.status === 'live' ? 'En vivo' : slot.status === 'paused' ? 'Pausada' : 'Pendiente'}</span></li>)}</ol><p className="mt-3 text-xs leading-5 text-secondary">Los pases directos no ocupan escenario. En eliminación directa, el duelo por tercer lugar precede a la gran final. Las revanchas son exhibiciones opcionales, fuera del campeonato.</p></details>
  </section>
}
